DROP TABLE JOB;
CREATE TABLE JOB (
    JNO NUMBER(2) PRIMARY KEY,
    JNAME VARCHAR2(30)
);
SELECT * FROM JOB;
DROP TABLE PERSON;

CREATE TABLE PERSON (
    NO NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(10),
    JNO NUMBER(2) REFERENCES JOB (JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
);
SELECT * FROM PERSON;

drop sequence person_no_sq;
CREATE SEQUENCE PERSON_NO_SQ 
MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '엠씨');


--1.
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL,'정우성',(SELECT JNO FROM JOB WHERE JNAME='배우'),90,80,81);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL,'박세영',(SELECT JNO FROM JOB WHERE JNAME='배우'),80,90,80);
INSERT INTO PERSON VALUES (PERSON_NO_SQ.NEXTVAL,'배수지',(SELECT JNO FROM JOB WHERE JNAME='가수'),20,90,90);

--2.
--1등 : 송혜교(5번) 배우 100 100 100 300 (총점순 내림차순으로)
SELECT NAME||'('||NO||'번)' NAME , JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM 
    FROM PERSON P , JOB J WHERE P.JNO=J.JNO AND JNAME='배우' ORDER BY SUM DESC; --FROM 절에 들어갈 서브쿼리.
    
SELECT ROWNUM RANK, S.* FROM (SELECT NAME||'('||NO||'번)' NAME , JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM 
    FROM PERSON P , JOB J WHERE P.JNO=J.JNO AND JNAME='배우' ORDER BY SUM DESC) S; --자바에서 2번 기능에 쓸 쿼리.


--3.
SELECT ROWNUM RANK, S.* FROM (SELECT NAME||'('||NO||'번)' NAME , JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM 
    FROM PERSON P , JOB J WHERE P.JNO=J.JNO ORDER BY SUM DESC) S;
    
    COMMIT;