-- 
DROP TABLE CUSTOMER; --
DROP TABLE CUSTOMER_LEVEL;  
DROP TABLE CUS_LEVEL;
DROP SEQUENCE CUSTOMER_SEQ;
--테이블 생성.
CREATE TABLE CUS_LEVEL(
    levelNO NUMBER(1, 0) PRIMARY KEY,
    levelNAME VARCHAR2 (20),
    LOW NUMBER(9) ,
    HIGH NUMBER(9)

);

CREATE TABLE CUSTOMER (
    cID NUMBER(6, 0) PRIMARY KEY,
    cTEL VARCHAR2(20) NOT NULL,
    cNAME VARCHAR2(30) NOT NULL,
    cPOINT NUMBER(9, 0) DEFAULT 1000,
    cAMOUNT NUMBER(9, 0) DEFAULT 0,
    levelNO NUMBER(1, 0) DEFAULT 1 REFERENCES CUS_LEVEL(levelNO)


);

CREATE SEQUENCE CUSTOMER_SEQ
MAXVALUE 999999;

--더미 데이터 INSERT
INSERT INTO CUS_LEVEL VALUES (1, 'NORMAL', 0, 999999); --레벨
INSERT INTO CUS_LEVEL VALUES (2, 'SILVER', 1000000, 1999999);
INSERT INTO CUS_LEVEL VALUES (3, 'GOLD', 2000000, 2999999);
INSERT INTO CUS_LEVEL VALUES (4, 'VIP', 3000000, 4999999);
INSERT INTO CUS_LEVEL VALUES (5, 'VVIP', 5000000, 999999999);
SELECT * FROM CUS_LEVEL;

INSERT INTO CUSTOMER (cID,cTEL,cNAME) VALUES (CUSTOMER_SEQ.NEXTVAL, '010-9999-9999','홍길동');
INSERT INTO CUSTOMER VALUES (CUSTOMER_SEQ.NEXTVAL, '010-8888-9999','김길동', 1000, 5000000, 5);
SELECT * FROM CUSTOMER;
COMMIT;
-- 0. 레벨 이름들 콤보박스에 나오게. LEVELNAMES PUBLIC VECTOR<STRING> LEVELNAMES() {}
SELECT LEVELNAME FROM CUS_LEVEL;
--1.아이디검색. PUBLIC CUSTOMERDTO cIDGETCUSTOMERS(STRING cID)  유일한 값이라 어레이X
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, HIGH-cAMOUNT+1 forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND cID=1;

--레벨 최대치인 사람의 다음 구매액 0으로 만들어야함. NULL이 자바로 가면 0으로 받는다. 서브쿼리혼자 실행이 안돼는데 FROM 을 혼자만 하고 WHERE 에 조인한것처럼 해서그럼. 따라서 전체로 돌려야 나옴.
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, 
    (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND cID=2;
-- 번호로 검색하는건 AND부분만 바꾸면댐.

--2. 번호뒷자리4자리로 검색, FULL 로 검색 PUBLIC ARRAYLIST<CUSTOMERDTO> cTELGETCUSTOMER(STRING cTEL)
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND cTEL LIKE '%'||'9999'; 
                    --'%010-9999-9999' ,  '%'||'9999' => '9999' 를 ? 로 바꿀수있음
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND cTEL LIKE '%010-9999-9999';

--3.이름 검색. PUBLIC ARRAYLIST<CUSTOMERDTO> cTELGETCUSTOMER(STRING cNAME)
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND cNAME = '홍길동'; 
    
--4. 포인트로 구매. PUBLIC INT BUYITHPOINT(INT cAMOUNT) UPDATE.
UPDATE CUSTOMER SET cPOINT = cPOINT - 500 WHERE cID= 1 ;  -- 얼마의 포인트를 쓴, 그사람의 ID
SELECT * FROM CUSTOMER;

--5.물품 구매. (포인트 변경, 구매누적금액 변경, [LEVELNO 변경. 특정 조건을 줘야 바뀌어야한다.] )
--5-1. 포인트와 구매누적금액 변경 쿼리.
UPDATE CUSTOMER SET cPOINT = cPOINT + 1000000*0.05, cAMOUNT = cAMOUNT + 1000000 WHERE cID=1;
--백만원 구매금액의 0.05 퍼센트 누적, 구매누적금액 변경.
SELECT * FROM CUSTOMER;
--5-2 LEVELNO 변경
SELECT cNAME, cAMOUNT, C.LEVELNO 현재레벨 ,L.LEVELNO 변경한레벨 , LOW,HIGH 
    FROM CUSTOMER C, CUS_LEVEL L WHERE cAMOUNT BETWEEN LOW AND HIGH;

SELECT L.LEVELNO 변경한레벨 
    FROM CUSTOMER C, CUS_LEVEL L WHERE cAMOUNT BETWEEN LOW AND HIGH AND cID = 1; --ID가 1인 회원의 수정할 레벨.
    
UPDATE CUSTOMER SET LEVELNO = (SELECT L.LEVELNO 변경한레벨 
    FROM CUSTOMER C, CUS_LEVEL L WHERE cAMOUNT BETWEEN LOW AND HIGH AND cID=1)
    WHERE cID= 1 ; -- 변경 완료.
    SELECT * FROM CUSTOMER;
-- 5-1 + 5-2 = 자바에 쓸 쿼리. PUBLIC INT BUY(INT cAMOUNT, cID)
UPDATE CUSTOMER SET cPOINT = cPOINT + 1000000*0.05, cAMOUNT = cAMOUNT + 1000000,
    LEVELNO = (SELECT L.LEVELNO 변경한레벨 
    FROM CUSTOMER C, CUS_LEVEL L WHERE cAMOUNT+1000000 BETWEEN LOW AND HIGH AND cID=1)WHERE cID=1;

SELECT * FROM CUSTOMER;
--WHERE 절에서 cAMOUNT(현 누적액)+(더 구매한 금액.)

--6.등급별 출력. PUBLIC ARRAYLIST<CUSTOMERDTO> LEVELNAME(STRING LEVELNAME)
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO AND LEVELNAME='VVIP' ORDER BY cAMOUNT DESC;
    
    SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5;
    
    
--7.전체출력 PUBLIC ARRAYLIST<CUSTOMERDTO> GETCUSTOMERS()  DTO타입 내용을 이렇게 나오게끔.
SELECT cID,cTEL,cNAME,cPOINT, cAMOUNT, LEVELNAME, (SELECT HIGH-cAMOUNT+1 FROM CUSTOMER WHERE cID=C.cID AND LEVELNO != 5) forlevelUp 
    FROM CUSTOMER C, CUS_LEVEL L WHERE C.LEVELNO=L.LEVELNO ;

--8.회원가입. 번호 이름으로 가입 PUBLIC INT INSERTCUSTOMER(STRING cTEL, STRING cNAME)
INSERT INTO CUSTOMER (cID,cTEL,cNAME) VALUES (CUSTOMER_SEQ.NEXTVAL, '010-7777-7777','신길동');
SELECT * FROM CUSTOMER;
--9.번호수정(전화번호 수정.) PUBLIC INT UPDATECUSTOMER(INT cID, STRING cTEL)
UPDATE CUSTOMER SET cTEL = '010-7777-7771' WHERE cID = 3;

--10. 탈퇴/.  PUBLIC INT DELETECUSTOMER (INT cID)
DELETE FROM CUSTOMER WHERE cID = 3;
COMMIT;