DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

CREATE TABLE CUS_LEVEL (
    LEVELNO NUMBER(10) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);
DESC CUS_LEVEL;
SELECT * FROM CUS_LEVEL;

INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');


CREATE SEQUENCE CUS_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 100
    MINVALUE 1
    NOCYCLE
    NOCACHE;

DROP SEQUENCE CUS_SEQ;

CREATE TABLE CUSTOMER (
    CNO NUMBER(5) PRIMARY KEY,
    CNAME VARCHAR2(20),
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR2(40) UNIQUE,
    POINT NUMBER(6),
    
    LEVELNO NUMBER(10) REFERENCES CUS_LEVEL (LEVELNO)
);
DESC CUSTOMER;
DROP TABLE CUSTOMER;
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE ,POINT, LEVELNO) 
    VALUES (CUS_SEQ.NEXTVAL, 'È«±æµ¿', '17/10/17', '010-9999-9999' ,300, 1);
    
INSERT INTO CUSTOMER (CNO, CNAME, JOINDATE, PHONE, POINT,LEVELNO) 
    VALUES (CUS_SEQ.NEXTVAL, 'ÀÌÃ¶¼ö','17/11/12','010-8888-8888',NULL,2);
SELECT * FROM USER_SEQUENCES;

SELECT CNO, CNAME, TO_CHAR(JOINDATE,'YYYY-MM-DD'), PHONE, POINT, LEVELNAME FROM CUS_LEVEL L , CUSTOMER C
    WHERE L.LEVELNO=C.LEVELNO;

