-- (III) JOIN : 테이블 2개이상을 연결하여 검색.
SELECT * FROM EMP WHERE ENAME = 'SCOTT'; --부서번호 (DEPTNO) :20
SELECT * FROM DEPT; 
-- CORSS JOIN (FROM 절에 테이블 2개 이상.)
SELECT * FROM EMP,DEPT WHERE ENAME = 'SCOTT';

--★EQUI JOIN (공통 필드의 DEPTNO 값이 일치되는 조건만 JOIN) 서로 다른 테이블의 찾고싶은 데이터의 같은것들만 불러오게.
SELECT * FROM EMP, DEPT WHERE ENAME = 'SCOTT' AND EMP.DEPTNO=DEPT.DEPTNO;  

SELECT * FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;

--모든 사원의 이름 , 부서명, 부서번호 출력. 테이블에도 별명을 선언하면 똑같이 써줘야한다.
SELECT ENAME 이름, DNAME, E.DEPTNO FROM EMP E,DEPT D WHERE E.DEPTNO = D.DEPTNO ORDER BY ENAME;
--가능하긴하나 생략가능  E.ENMAE D.DNAME   , 테이블 별명은 30자 넘으면 안댐.  
SELECT E.*, DNAME,LOC FROM EMP E , DEPT D WHERE E.DEPTNO=D.DEPTNO;

--사번, 이름, 부서번호 ,부서이름 , 근무지
SELECT EMPNO,ENAME , E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;

--필드 출력.이름,업무,급여,부서명, 근무지. 급여 2000이상인 직원만 출력
SELECT ENAME, JOB,SAL, DNAME,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.SAL>=2000;

--근무지(LOC) 이 CHICAGO인 사람의 이름 ,업무 , 부서명, 근무지 필드 출력
SELECT ENAME ,JOB, DNAME,LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.LOC='CHICAGO';

--부서번호가 10 또는 20 인 사원의 이름, 업무 ,근무지 출력.(급여순으로 정렬.) [E.DEPTNO IN (10,20) => E.DEPTNO 나 D. 나 같다.]
SELECT ENAME, JOB, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.DEPTNO IN (10,20) ORDER BY SAL;

--이름, 급여, 상여금(COMM),연봉((급여+COMM)*12), 부서명, 근무지
SELECT ENAME , SAL, COMM, (SAL+NVL(COMM,0))*12 "연봉", DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;

--T0_CHAR 는 다음에 제대로.

--이름, 급여, 상여금(COMM),연봉((급여+COMM)*12), 부서명, 근무지 [JOB이 SALESMAN 또는 MANAGER 인 사원만 출력+연봉이 큰 순으로 정렬]
SELECT ENAME , SAL, COMM, (SAL+NVL(COMM,0))*12 "연봉", DNAME, LOC FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND JOB IN ('SALESMAN','MANAGER') ORDER BY 연봉 DESC;
            
-- 소문자를 대문자로 바꿔주는 UPPER            
SELECT ENAME , SAL, COMM, (SAL+NVL(COMM,0))*12 "연봉", DNAME, LOC FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND JOB IN (UPPER('salesman'), UPPER('manager')) ORDER BY 연봉 DESC;            

--대문자와 소문자가 있는지 모를때와 같이 있을때. UPPER(JOB)
--WHERE E.DEPTNO=D.DEPTNO AND UPPER(JOB) IN (UPPER('SALESMAN'), UPPER('manager')) ORDER BY 연봉 DESC;

--COMM이 NULL 이고 급여가 1200 이상인 사원의 이름, 급여, 입사일, 부서번호, 부서명(부서명 순으로 정렬 부서명이 같으면 급여큰순으로 정리)
SELECT ENAME , SAL ,HIREDATE , E.DEPTNO, DNAME FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND COMM IS NULL AND SAL>=1200 ORDER BY DNAME, SAL DESC;

--EQUIT JOIN 예제.

--뉴욕에서 근무하는 사원의 이름과 급여를 출력하시오
SELECT * FROM DEPT;
SELECT ENAME , SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC='NEW YORK';
--ACCOUNTING 부서 소속 사원의 이름과 입사일을 출력하시오
SELECT ENAME, HIREDATE FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND DNAME='ACCOUNTING';
--직급이 MANAGER인 사원의 이름, 부서명을 출력하시오
SELECT ENAME, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND JOB='MANAGER';
--Comm이 null이 아닌 사원의 이름, 급여, 부서번호, 근무지를 출력하시오.
SELECT ENAME, SAL ,E.DEPTNO , LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND NOT COMM IS NULL;
SELECT ENAME, SAL ,E.DEPTNO , LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND  COMM IS NOT NULL;


--★ NON-EQUI JOIN
SELECT ENAME , SAL FROM EMP WHERE ENAME = 'SCOTT';
SELECT * FROM SALGRADE; --셀그레이드 월급의 등급.  LOSAL HISAL = SALGRADE 안에 있는 녀석들.
SELECT ENAME , SAL, GRADE, LOSAL, HISAL FROM EMP , SALGRADE WHERE ENAME='SCOTT' AND SAL>=LOSAL AND SAL<=HISAL;
                                                                            --AND SAL BETWEEN LOSAL AND HISAL;    
                                                                            
--모든 사원의 사번, 이름, JOB ,  상사사번 , 급여, 급여등급(1등급 ,2등급 ~ .. )출력.
SELECT EMPNO, ENAME , JOB , MGR , SAL , GRADE||'등급' FROM EMP, SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL;

--연습문제.
--	Comm이 null이 아닌 사원의 이름, 급여, 등급, 부서번호, 부서이름, 근무지를 출력하시오.
SELECT ENAME, SAL, GRADE, E.DEPTNO, DNAME, LOC FROM EMP E, DEPT D, SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;
                
--	이름, 급여, 입사일, 급여등급
SELECT ENAME, SAL, HIREDATE, GRADE FROM EMP, SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL;

--	이름, 급여, 입사일, 급여등급, 부서명, 근무지
SELECT ENAME , HIREDATE , GRADE, DNAME , LOC FROM EMP E, DEPT D, SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL; 

--	이름, 급여, 등급, 부서코드, 근무지. 단 comm 이 null아닌 경우
SELECT ENAME , SAL , GRADE , D.DEPTNO, LOC FROM EMP E, DEPT D, SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND COMM IS NOT NULL;

--	이름, 급여, 급여등급, 연봉, 부서명, 부서별 정렬, 부서가 같으면 연봉순. 연봉=(sal+comm)*12 comm이 null이면 0
SELECT ENAME, SAL ,GRADE, (SAL+NVL(COMM, 0))*12 연봉, DNAME FROM EMP E , DEPT D , SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL ORDER BY DNAME, 연봉;

--	이름, 업무, 급여, 등급, 부서코드, 부서명 출력. 급여가 1000~3000사이. 정렬조건 : 부서별, 부서같으면 업무별, 업무같으면 급여 큰순
SELECT ENAME , JOB, SAL , GRADE , D.DEPTNO, DNAME FROM EMP E, DEPT D, SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND SAL>=1000 AND SAL<=3000 ORDER BY DNAME, JOB,SAL DESC;

--	이름, 급여, 등급, 입사일, 근무지. 81년에 입사한 사람. 등급 큰순
SELECT ENAME , SAL , GRADE, HIREDATE, LOC FROM EMP E , DEPT D , SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND TO_CHAR(HIREDATE,'YY') = '81' ORDER BY GRADE DESC;


--★SELF JOIN 나랑 나랑.WORKER = W , MANAGER = M
SELECT W.EMPNO , W.ENAME , W.MGR, M.ENAME "MANAGERNAME" FROM EMP W, EMP 
    WHERE W.ENAME = 'SMITH' AND W.MGR=M.EMPNO;

SELECT WORKER.EMPNO, WORKER.ENAME, MANAGER.ENAME FROM EMP WORKER, EMP MANAGER 
    WHERE WORKER.MGR=MANAGER.EMPNO; --EMPNO 에 NULL값이 없으므로 13명만 나옴.

--스미스의 상사는 포드다. 라고 출력하기.
SELECT W.ENAME||'의 상사는 '||M.ENAME||'다' FROM EMP W, EMP M WHERE W.MGR=M.EMPNO;

-- 1.상사의 이름이 KING 인 사원들의 이름과 JOB 출력--셀프
SELECT W.ENAME , W.JOB FROM EMP W, EMP M WHERE W.MGR=M.EMPNO AND M.ENAME='KING';

--2.스콧과 동일한 부서 번호에서 근무하는 사람의 이름 출력--셀프
SELECT E1.ENAME, E1.DEPTNO, E2.DEPTNO, E2.ENAME FROM EMP E1, EMP E2 
    WHERE E1.ENAME='SCOTT' AND E1.DEPTNO=E2.DEPTNO AND E2.ENAME != 'SCOTT';
                    
SELECT E2.ENAME FROM EMP E1, EMP E2 
    WHERE E1.ENAME='SCOTT' AND E1.DEPTNO=E2.DEPTNO AND E2.ENAME != 'SCOTT';                    
                    
--3.스콧과 동일한 근무지에서 근무하는 사람의 이름 출력.--셀프,EQUI
SELECT E1.ENAME, D1.LOC FROM EMP E1, DEPT D1 WHERE E1.DEPTNO=D1.DEPTNO AND E1.ENAME='SCOTT';--1번
SELECT E2.ENAME , D2.LOC FROM EMP E2, DEPT D2 WHERE E2. DEPTNO=D.DEPTNO;--2번

SELECT E2.ENAME FROM EMP E1, DEPT D1, EMP E2, DEPT D2 
    WHERE E1.DEPTNO=D1.DEPTNO AND E2. DEPTNO=D2.DEPTNO AND E1.ENAME='SCOTT' AND D1.LOC=D2.LOC AND E2.ENAME != 'SCOTT';
INSERT INTO DEPT VALUES (50,'IT','DALLAS'); -- 2,3 의 문제가 같기때문에 데이터를 하나 추가함.
INSERT INTO EMP (EMPNO,ENAME,DEPTNO) VALUES (9999,'HONG',50); --추가구절을 만들고 실행시켜야 추가댐.
ROLLBACK;  --데이터 조작어 취소. 


--Outer Join => (+) 조인조건에 만족하지않은 행까지 나타나게
SELECT W.EMPNO, W.ENAME, M.ENAME FROM EMP W, EMP M WHERE W.MGR=M.EMPNO(+);
SELECT W.EMPNO, W.ENAME, NVL(M.ENAME, '-CEO-') FROM EMP W, EMP M WHERE W.MGR=M.EMPNO(+);
SELECT W.EMPNO, W.ENAME, M.ENAME FROM EMP W, EMP M WHERE W.MGR(+)=M.EMPNO; --(+)를 왼쪽에 뿌린경우.
SELECT W.EMPNO, W.ENAME, M.ENAME FROM EMP W, EMP M WHERE W.MGR(+)=M.EMPNO AND W.EMPNO IS NULL;--한마디로 상사없는 사원들.

SELECT * FROM EMP;--14행
SELECT * FROM DEPT; --4행 (10 20 30 40)
SELECT E.*, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO(+)=D.DEPTNO; --없어서 안나오는쪽에 다가 (+)를 붙힌다.

--아웃터 조인 예제.
--스미스의 매니저는 포드 입니다. 라고 출력./ 킹의 매니저는 없다.
SELECT W.ENAME||'의 상사는 '||NVL(M.ENAME, '無')||' 입니다.' FROM EMP W, EMP M WHERE W.MGR=M.EMPNO(+);



--★JOIN 연습문제

--1. 이름, 직속상사
SELECT W.ENAME , M.ENAME FROM EMP W , EMP M WHERE W.MGR=M.EMPNO;

--2. 이름, 급여, 업무, 직속상사
SELECT W.ENAME, W.SAL , W.JOB, M.ENAME FROM EMP W, EMP M WHERE W.MGR=M.EMPNO;

--3. 이름, 급여, 업무, 직속상사. (상사가 없는 직원까지 전체 직원 다 출력.
    --상사가 없을 시 '없음'으로 출력)
SELECT W.EMPNO, W.SAL , W.JOB, NVL(M.ENAME, '없음')  FROM EMP W, EMP M  WHERE W.MGR=M.EMPNO(+);

--4. 이름, 급여, 부서명, 직속상사명
SELECT W.ENAME , W.SAL,D.DNAME, M.ENAME FROM EMP W, EMP M, DEPT D WHERE D.DEPTNO=W.DEPTNO AND W.MGR=M.EMPNO;
SELECT * FROM DEPT D ;
--5. 이름, 급여, 부서코드, 부서명, 근무지, 직속상사명, (상사가 없는 직원까지 전체 직원 다 출력)
SELECT W.ENAME , W.SAL,W.DEPTNO,D.DNAME, LOC,NVL(M.ENAME, '없음') FROM EMP W, EMP M, DEPT D WHERE W.MGR=M.EMPNO(+) AND D.DEPTNO=W.DEPTNO ;

--6. 이름, 급여, 등급, 부서명, 직속상사명. 급여가 2000이상인 사람
SELECT W.ENAME, W.SAL , GRADE, D.DNAME , M.ENAME FROM EMP W, EMP M ,SALGRADE,DEPT D
    WHERE W.MGR=M.EMPNO(+) AND D.DEPTNO=W.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL AND W.SAL>=2000;

--7. 이름, 급여, 등급, 부서명, 직속상사명, (직속상사가 없는 직원까지 전체직원 부서명 순 정렬)
SELECT W.ENAME, W.SAL , GRADE, D.DNAME , M.ENAME FROM EMP W, EMP M, SALGRADE, DEPT D 
    WHERE W.MGR=M.EMPNO(+) AND D.DEPTNO=W.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL ORDER BY DNAME;

--8. 이름, 급여, 등급, 부서명, 연봉, 직속상사명. 연봉=(급여+comm)*12 단 comm이 null이면 0
SELECT W.ENAME , W.SAL, GRADE , D.DNAME, (W.SAL+NVL(W.COMM, 0))*12 "연봉", M.ENAME FROM EMP W,EMP M, SALGRADE ,DEPT D 
    WHERE W.MGR=M.EMPNO(+) AND D.DEPTNO=W.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL  ;
--이밑 문제는 상단에 참고용으로.
SELECT ENAME, SAL ,GRADE, (SAL+NVL(COMM, 0))*12 연봉, DNAME FROM EMP E , DEPT D , SALGRADE 
    WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL ORDER BY DNAME, 연봉;

--9. 8번을 부서명 순 부서가 같으면 급여가 큰 순 정렬
SELECT W.ENAME, W.SAL, GRADE, DNAME, (W.SAL+NVL(W.COMM, 0))*12 , M.ENAME FROM EMP W, EMP M,SALGRADE,DEPT D 
    WHERE W.MGR=M.EMPNO(+) AND D.DEPTNO=W.DEPTNO AND W.SAL BETWEEN LOSAL AND HISAL ORDER BY W.SAL DESC;

--  PART2
--1.EMP 테이블에서 모든 사원에 대한 이름,부서번호,부서명을 출력하는 SELECT 문장을 작성하여라.
SELECT ENAME , D.DEPTNO , DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO;
SELECT * FROM DEPT;
SELECT * FROM EMP;

--2. EMP 테이블에서 NEW YORK에서 근무하고 있는 사원에 대하여 이름,업무,급여,부서명을 출력
SELECT ENAME, JOB,SAL, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND LOC='NEW YORK' ;
SELECT * FROM TAB;

--3. EMP 테이블에서 보너스를 받는 사원에 대하여 이름,부서명,위치를 출력
SELECT ENAME, DNAME, LOC FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND COMM IS NOT NULL AND COMM !=0;

--4. EMP 테이블에서 이름 중 L자가 있는 사원에 대하여 이름,업무,부서명,위치를 출력
SELECT ENAME, JOB, DNAME, LOC FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND ENAME LIKE '%L%';

--5. 사번, 사원명, 부서코드, 부서명을 검색하라. 사원명기준으로 오름차순정열
SELECT EMPNO, ENAME, D.DEPTNO, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO ORDER BY ENAME;

--6. 사번, 사원명, 급여, 부서명을 검색하라. 
    --단 급여가 2000이상인 사원에 대하여 급여를 기준으로 내림차순으로 정열하시오
SELECT EMPNO, ENAME, SAL, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL>=2000 ORDER BY SAL DESC;

--7. 사번, 사원명, 업무, 급여, 부서명을 검색하시오. 단 업무가 MANAGER이며 급여가 2500이상인
-- 사원에 대하여 사번을 기준으로 오름차순으로 정열하시오.
SELECT EMPNO, ENAME, JOB, SAL, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND JOB='MANAGER' AND SAL>=2500 ORDER BY EMPNO;

--8. 사번, 사원명, 업무, 급여, 등급을 검색하시오. 단, 급여기준 내림차순으로 정렬하시오
SELECT EMPNO, ENAME, JOB, SAL, GRADE FROM EMP, SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL ORDER BY SAL DESC;

--9. 사원테이블에서 사원명, 사원의 상사를 검색하시오(상사가 없는 직원까지 전체)
SELECT W.ENAME 사원명 , M.ENAME MANAGER FROM EMP W , EMP M WHERE W.MGR=M.EMPNO(+);

--10. 사원명, 상사명, 상사의 상사명을 검색하시오 (셀프조인 두번함.)
SELECT W.ENAME , M.ENAME , MM.ENAME FROM EMP W, EMP M , EMP MM WHERE W.MGR=M.EMPNO AND M.MGR=MM.EMPNO;

--11. 위의 결과에서 상위 상사가 없는 모든 직원의 이름도 출력되도록 수정하시오
SELECT W.ENAME , NVL(M.ENAME, ' '), NVL(MM.ENAME,' ') FROM EMP W, EMP M , EMP MM WHERE W.MGR=M.EMPNO(+) AND M.MGR=MM.EMPNO(+);

------

