SELECT * FROM DEPT ;
INSERT INTO DEPT VALUES (50,'IT','SEOUL');
COMMIT;
UPDATE DEPT SET LOC = 'PUSAN' WHERE DEPTNO = 50;

SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 30;
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP ;
select * from dept;
SELECT EMPNO, ENAME, SAL, DEPTNO FROM EMP WHERE DEPTNO = 10;

SELECT W.EMPNO, W.ENAME, W.SAL ,M.ENAME FROM EMP W, EMP M WHERE W.MGR=M.EMPNO ;

SELECT W.EMPNO, W.ENAME, M.ENAME "manager" ,W.SAL FROM EMP W, EMP M WHERE W.MGR=M.EMPNO and w.deptno= 20; --EMPNO 에 NULL값이 없으므로 13명만 나옴.

SELECT * FROM DEPT WHERE DNAME='SALES';

SELECT EMPNO, ENAME, SAL, GRADE FROM EMP , SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL;

SELECT * FROM EMP E, DEPT D, SALGRADE WHERE E.DEPTNO=D.DEPTNO AND SAL BETWEEN LOSAL AND HISAL AND DNAME= 'SALES';

SELECT * FROM DEPT WHERE DNAME= 'SALES';
SELECT * FROM DEPT;


-- ===






