SHOW USER;
SELECT * FROM TAB;
SELECT * FROM DBA_TABLES; --DBA 권한이 아니라 접근불가.
SELECT * FROM USER_TABLES; --내 계정이 갖고있는 테이블 정보
SELECT * FROM ALL_TABLES; --접근가능한 테이블 정보
SELECT * FROM ALL_TABLES WHERE TABLE_NAME='EMP';
SELECT * FROM SCOTT.EMP; --스콧계정의 EMP테이블 보기
EXIT;  --접속 해제.
SHOW USER;
SELECT * FROM SCOTT.EMP;  --권한 박탈 후 접근 불가.
SELECT * FROM ALL_TABLES WHERE TABLE_NAME='EMP';
EXIT;