--DROP TABLE STUDENT1;
DROP TABLE STUDENT;
DROP TABLE MAJOR;
DROP SEQUENCE  STUDENT_SEQ;




--CREATE TABLE 어제한거 참조.
CREATE TABLE MAJOR (
    mNO NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(50)

); 

CREATE TABLE STUDENT (
    sNO VARCHAR2(7) PRIMARY KEY,
    sNAME VARCHAR2(30),
    mNO NUMBER(2) REFERENCES MAJOR (mNO),
    SCORE NUMBER(3) DEFAULT 0 CHECK (SCORE >=0 AND SCORE <= 100),
    EXPEL NUMBER(1) DEFAULT 0 CHECK (EXPEL =0 OR EXPEL= 1)
);

--CREATE SEQ 어제 한거 참조.
DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ
    MAXVALUE 999999
    NOCYCLE
    NOCACHE;
--2021001 만드는쿼리
SELECT TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')) FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY')||LPAD(STUDENT_SEQ.NEXTVAL, 3, '0') FROM DUAL;

SELECT * FROM USER_SEQUENCES;
SELECT STUDENT_SEQ.CURRVAL FROM DUAL;

--INSERT INTO FRIEND (NUM,NAME,PHONE) VALUES (FRIEND_SEQ.NEXTVAL,'홍길동','010-9999-9999');
    INSERT INTO MAJOR VALUES (1, '빅데이터학');
	INSERT INTO MAJOR VALUES (2, '경영정보학');
	INSERT INTO MAJOR VALUES (3, '컴퓨터공학');
	INSERT INTO MAJOR VALUES (4, '소프트웨어');
	INSERT INTO MAJOR VALUES (5, '인공지능학');	
ROLLBACK;

SELECT * FROM MAJOR;
SELECT * FROM STUDENT;
--학생 입력.
INSERT INTO STUDENT (sNO, sNAME, mNO, SCORE) VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '정우성', (SELECT mNO FROM MAJOR WHERE mNAME='빅데이터학'),90);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '박세영', (SELECT mNO FROM MAJOR WHERE mNAME='빅데이터학'),80,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '배수지', (SELECT mNO FROM MAJOR WHERE mNAME='컴퓨터공학'),20,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '홍길동', (SELECT mNO FROM MAJOR WHERE mNAME='경영정보학'),95,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '송혜교', (SELECT mNO FROM MAJOR WHERE mNAME='인공지능학'),100,0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '홍철수', (SELECT mNO FROM MAJOR WHERE mNAME='소프트웨어'),10,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '김제적', (SELECT mNO FROM MAJOR WHERE mNAME='컴퓨터공학'),20,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '정우성', (SELECT mNO FROM MAJOR WHERE mNAME='인공지능학'),32,1);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '신길동', (SELECT mNO FROM MAJOR WHERE mNAME='경영정보학'),40,0);
COMMIT;
UPDATE STUDENT SET SCORE=50 WHERE sNO='2021003';


SELECT mNAME FROM MAJOR; -- 전공들을 콤보박스에 추가하기.
SELECT sNO, sNAME, mNAME , SCORE FROM STUDENT S, MAJOR M WHERE S.mNO=M.mNO AND sNO = '2021001'; --학번검색
SELECT sNO, sNAME , mNAME, SCORE FROM STUDENT S, MAJOR M WHERE S.mNO=m.mNO AND sNAME = '정우성'; -- 이름 검색
SELECT ROWNUM RANK, sNAME||'('||sNO||')' sNAME, mNAME, SCORE FROM (SELECT * FROM STUDENT S, MAJOR M WHERE S.mNO=m.mNO AND  mNAME = '컴퓨터공학'); -- 전공검색
UPDATE STUDENT SET sNAME='신길동', mNO=(SELECT mNO FROM MAJOR WHERE mNAME='인공지능학'), SCORE = 50 WHERE sNO='2021009'; --학생수정.
SELECT ROWNUM RANK, sNAME||'('||sNO||')'sNAME,mNAME||'('||mNO||')'mNAME, SCORE   -- 제적자 제외 학생출력.
    FROM (SELECT S.*, mNAME FROM STUDENT S, MAJOR M WHERE S.mNO=M.mNO AND EXPEL=0 ORDER BY SCORE DESC);
SELECT ROWNUM RANK, sNAME||'('||sNO||')'sNAME, mNAME||'('||mNO||')'mNAME, SCORE --제적자 출력.
    FROM (SELECT S.*, mNAME FROM STUDENT S, MAJOR M WHERE S.mNO=M.mNO AND EXPEL=1 ORDER BY SCORE DESC);
SELECT mNO FROM MAJOR WHERE mNAME= ?;
UPDATE STUDENT SET EXPEL=1 WHERE sNO='2021009';  --제적처리

COMMIT;