SELECT * FROM DEPT;

CREATE OR REPLACE VIEW DEPT0
    AS SELECT * FROM DEPT; 
    
SELECT * FROM DEPT0;
INSERT INTO DEPT0 VALUES (50, 'AI', '51S');
UPDATE DEPT0 SET LOC='SCP' WHERE DEPTNO=50;
ROLLBACK;
COMMIT;

select * from tab;